USE [MaskDetektorDataBase]

CREATE TABLE [dbo].[$TAB$](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Photo] [image] NULL,
	[PhotoName] [nvarchar](255) NULL,
	[PhotoExtension] [nvarchar](20) NULL,
	[Date] [datetime] NULL,
 CONSTRAINT [PK_$TAB$] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]



